- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install default packages
  ansible.builtin.apt:
    name:
      - net-tools
      - dnsutils
      - wget
      - curl
      - mc
      - rsync
    state: present
